services:
  app_vet:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - veterinaria
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://veterinaria:3306/veterinaria
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  veterinaria:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "veterinaria"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
